// Seed to create company name.
export const name = [
    'Aztec',
    'Polka',
    'Wolf',
    'Bay',
    'Easter',
    'Motley',
    'Meyer',
    'Forestal',
    'Yu',
    'Kyoto',
    'Faccio',
    'Monster',
    'Norris',
    'Leonhard',
    'Koshi',
    'Fabucci',
    'Taiwan',
    'Peruvian',
    'Lady',
    'Holy',
    'Martian'
];

// Seed to compliment camp name.
export const location = [
    'Mountain',
    'River',
    'Valley',
    'Arcs',
    'Hiding',
    'Desert',
    'Hill',
    'Hotel',
    'Resort',
    'Bar & Grill',
    'Flowers',
    "Air",
    'Reserve',
    'National Park',
    'Bridge',
    'Skyscraper',
    'Woods',
    'Forest',
    'Jungle',
    'Cabin',
    'Igloo',
    'Hut'
];
